### ISSUE TITLE
Working with Nan values

### ISSUE THREAD

**Issue by kothawadegs** [creare-com/pydem#12]
I tried pyDEM on SRTM data, I'm able to calculate TWI, but in the final output, I'm getting Nan values as well. Can you please help me how to resolve this issue or is there any pre-processing required?  Also can you please add a comment on visualization part of the TWI on the map, like Folium etc?

**Comment by mpu-creare** [comment]
NaNn values are reasonable since twi = log(uca / slope) and in certain regions the slope is '0' . 

Do you get single pixel nan's? or do they come in larger groups? 
Can you send us a 5x5 grid of elevation, aspect, slope, uca, and twi around one of the single pixel nan's? 

Not sure what you're asking about the visualization...

**Comment by kothawadegs** [comment]
I'm getting ndarray containing TWI values. My question here is how to plot/visualize these values of TWI?

**Comment by mpu-creare** [comment]
Oh! There are a lot of ways to do so. I personally just use plain old matplotlib:
```python
from matplotlib.pyplot import *
matshow(twi)
show()
```

**Comment by kothawadegs** [comment]
Thanks..! What if I want to overlay this information in Folium map to validate the results with the actual geographical feature?

**Comment by mpu-creare** [comment]
I have not used Folium, so unfortunately I cannot comment on that. I have saved the results to a GeoTIFF and then used QGis to visualize / overlay.

**Comment by kothawadegs** [comment]
I used matshow to show and save the output. It's looking like the image attached here. Is there any way to make it better visualization?
![srtm1arcbangsouth](https://user-images.githubusercontent.com/8245778/32219008-c1e26ae2-be52-11e7-9bb8-f288cf135fec.png)

**Comment by mpu-creare** [comment]
I'm not sure what your goal is for your visualization. I suggest looking at matplotlib's documentation, as visualization is not one of pydem's core functions.
