### ISSUE TITLE
Problems with Taudem

### ISSUE THREAD

**Issue by diafu** [creare-com/pydem#18]
Hi, the link in your instructions for the Taudem source for windows: http://svn.mapwindow.org/svnroot/MapWindow4Dev/Bin/Taudem5Exe/ is not working. Trying to go around the problem, I installed Taudem following the instructions in their website for windows, and although Taudem was properly working, when I try to run pydem in one of your examples, i.e. elev, ang, test_data = get_test_data(testnum, NN) it returns the message: "Taudem did not complete. Is it installed properly?". After that I manually copy the executables from the Taudem installation found in the folder C:\Program Files\TauDEM\TauDEM5Exe to a folder you suggested: <ANACONDA_ROOT>\<lib><site-packages>\pydem\taudem\taudem_Windows and I still get the message: "Taudem did not complete. Is it installed properly?".  

Thanks for your help,

**Comment by mpu-creare** [comment]
Thanks for letting me know the link is broken. I'll look into it when I get a chance (might be a long time...). 

Incidentally, pydem doesn't require tauDEM to work -- we just used it to validate that we implemented everything correctly.

**Comment by diafu** [comment]
The problem was related with the path to "msvcr90.dll"; I solved with instructions here: https://stackoverflow.com/questions/14552348/runtime-error-r6034-in-embedded-python-application
