### ISSUE TITLE
How to install taudem? 

### ISSUE THREAD

**Issue by mehulkasliwal** [creare-com/pydem#19]
I tried installing taudem through the Windows installer downloaded from original website. Even after installing it, when I run an example code it raises the following exception:
File "C:\Anaconda3\envs\codefundo\lib\site-packages\pydem\taudem\taudem.py", line 33, in _run
    raise Exception("Taudem did not complete. Is it installed properly?")
Exception: Taudem did not complete. Is it installed properly?

**Comment by mpu-creare** [comment]
Let me know if #18 helps you as well. 

**Note**: Taudem is **NOT** needed for pydem to run. It's just used as a reference implementation. 

...I need to update some of the installation instructions.

**Comment by mpu-creare** [comment]
Closing -- stale.
