### ISSUE TITLE
Python 3 release open issues

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/pydem#21]
* [x] Need to fix Geotiff write out when the tiles are not contiguous
* [x] Need mechanism to pass parameters through compute manager to demprocessor
* [x] Need a helper function to compute everything needed to run any of the process functions
* [ ] Need to fix the order of operations for the edge-fixing so that each tile is at least visited once before any other tile is processed a second time. That just gets 99% of the tile-to-tile errors

**Comment by bgriffen** [comment]
Just checking - was the development branch a working python3+ version or still a work in progress that now now been archived? pyDEM seems to be the one of the only good options, though perhaps not converted to python3 yet? Are there alternatives you might suggest?

**Comment by mpu-creare** [comment]
For basic single-tile TWI processing, the develop branch should meet your Python3 needs. 

I'm also happy to accept merge requests to the main branch to make a pip-installable Python3 version of PyDEM, I just don't have time to work on it myself.

**Comment by mpu-creare** [comment]
See #25 . Finally had time to release Python 3 version. Should by up on PYPI soon.
