### ISSUE TITLE
Cannot open source file: 'pydem\cyfuncs\cyutils.c'

### ISSUE THREAD

**Issue by sahiggin** [creare-com/pydem#3]
Hi there,

I am trying to install pydem on a Windows 7 system, and I am getting the error "Cannot open source file: 'pydem\cyfuncs\cyutils.c'" Is that something that should be copied from my cython installation, or should that come with the pydem download?

Thanks,
Stephanie

**Comment by mpu-creare** [comment]
Hi Stephanie, 

pydem\cyfuncs\cyutils.c should be generated by cython when pydem is installed. 

Can you send me the output of your console when you're installing the software?

**Comment by mpu-creare** [comment]
@sahiggin did you manage to get this resolved?

**Comment by mpu-creare** [comment]
I'm closing this one because I didn't hear back. I'm happy to reopen if anyone can reproduce.
