### ISSUE TITLE
Check for python version before installing

### ISSUE THREAD

**Issue by gastoneb** [creare-com/pydem#8]
Pydem requires python 2.7 but somehow I was able to install and import the library using python 3.5. Needless to say my application failed. 

Unrelated feature request: It would be useful to be able to instantiate DEMProcessor from a 2D numpy array rather than passing the name to a tif file.

**Comment by mpu-creare** [comment]
Agreed, should check python version. Will look into it.

Agreed. that would be a useful feature. Feel free to make a push request if manage to fix it.

**Comment by mpu-creare** [comment]
Added a requirement for python 2.7 in version [0.2.0](https://github.com/creare-com/pydem/releases/tag/0.2.0) . 

Added ability to instantiate a DEMProcessor from a 2D numpy array, rather than passing the name to a tif file.
